# NT/SettingsBundle/Resources/config/admin.yml
services:
    sonata.admin.settings:
        class: NT\SettingsBundle\Admin\SettingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "nt_settings", label: "nt_settings" }
        arguments:
            - ~
            - NT\SettingsBundle\Entity\Setting
            - ~
        calls:
            - [ setTranslationDomain, [NTSettingsBundle]]