imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@NTTranslationsBundle/Resources/config/admin.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: bg
    locales: %a2lix_translation_form.locales%
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin
    sonata.media.admin.gallery.class: Application\Sonata\MediaBundle\Admin\GalleryAdmin
    sonata.media.admin.media.class: Application\Sonata\MediaBundle\Admin\MediaAdmin
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'NTCoreBundle:Form:tree_field.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'NTFrontendBundle:Admin:media_widgets.html.twig'
    # form_themes:
            - 'ReCaptchaBundle::form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    node: /usr/bin/node
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifycss
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        options:
             1002:  "SET NAMES 'UTF8'"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    translatable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translatable\Entity
                        # make sure vendor library location is correct
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                    loggable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                    tree:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                filters:
                    softdeleteable:
                        class:   Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                    softdeleteabletrash:
                        class: NT\CoreBundle\Filter\SoftDeleteableTrashFilter
                        enabled: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_admin:
    title_logo: '/images/logo.png'

    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'single_image'              # 'both', 'single_text' or 'single_image'
    templates:
        # default global templates
        layout:  ::baseadmin.html.twig
        show:    ApplicationSonataUserBundle:Admin:custom_show.html.twig
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            DELETE: DELETE
            EXPORT: EXPORT
            HISTORY: HISTORY
            MASTER: MASTER
    dashboard:
        groups:
            content:
                label: label.site
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - nt_menu.admin.menu
                    - nt.slider.admin.slider
                    - nt.accents.admin.accents
                    - nt.content.admin.content
                    - nt.admin.dealers

            projects:
                label: label.projects
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - nt.projects.admin.projects

            news:
                label: label.news
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - nt.news.admin.news

            settings:
                label: label.settings
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - sonata.admin.settings
                    - nt.translations.admin.translations
            media:
                label: label.media
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - sonata.media.admin.gallery
                    - sonata.media.admin.media
            users:
                label: label.administration
                label_catalogue: SonataAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.admin.block.search_result:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        nt.block.service:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        # Your other blocks

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_media:
    # if you don't use default namespace configuration
    # class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                # - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 75}
                big:   { width: 225, height: 169, quality: 75}
        nt_content:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                index:  { width: 1001, height: 747, quality: 75 }

        nt_slider:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                index:  { width: 1170, height: 200, quality: 75 }
                admin:  { width: 150, height: 80, quality: 75 }

        nt_accents:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                index:  { width: 200, height: 215, quality: 75 }

        nt_news_images:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                index:  { width: 360, height: 245, quality: 75 }
                thumb:  { width: 70, height: 70, quality: 75 }

        nt_projects_image:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                index:  { width: 265, height: 190, quality: 75 }

        nt_projects_gallery:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                thumb:  { width: 120, height: 120, quality: 75 }

        # inline_gallery:
        #     download:
        #         strategy: sonata.media.security.public_strategy
        #         mode: http
        #     providers:
        #         - sonata.media.provider.image
        #     formats:
        #         thumb:  { width: 282, height: 211, quality: 75 }

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
    providers:
        image:
            resizer: sonata.media.resizer.custom
            allowed_extensions: ['gif', 'jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/gif', 'image/png', 'image/jpg', 'image/jpeg']
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'zip', 'doc', 'docx', 'odt', 'csv', 'rar']
            allowed_mime_types: ['application/pdf', 'application/x-pdf',application/x-rar-compressed, application/x-rar, application/octet-stream, application/zip, application/octet-stream, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.oasis.opendocument.text, application/csv, inode/x-empty, text/plain]
# Twig Configuration


fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  test
    user_class:     \Application\Sonata\UserBundle\Entity\User


    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                       # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    # resetting:
    #     email:
    #         template: ApplicationSonataUserBundle:Email:resetting.email.twig
    #         from_email:
    #             address:        resetting@kontrax.com
    #             sender_name:    Kontrax

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: NTFrontendBundle:Menu:main_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
sensio_framework_extra:
    request:
        converters: true

nt_translations:
    fallback_locale: bg      # (required) default locale to use
    managed_locales: [bg, en, de]    # (required) locales that the bundle have to manage

a2lix_translation_form:
    locales: [bg, en, de]       # [1]
    required_locales: [bg]      # [2]
    manager_registry: doctrine      # [3]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [4]

services:
    nt.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: 'twig.extension' }

re_captcha:
    public_key: 6LfBUhgTAAAAAMilSJ0bjzJHRABZWxfK5t4j5I-9
    private_key: 6LfBUhgTAAAAAOAcm3Z0pB-bHM3W5B7czoFfXc67
    locale: "%locale%"

nt_tiny_mce:
    table_class_list: [ {title: 'Таблица', value: ''},{title: 'Таблица с основни стилове', value: 'tableMain'},{title: 'Таблица разделител', value: 'tableGrid'} ]
    link_class_list: [ {title: 'Линк', value: ''},{title: 'Бутон', value: 'btnArticle'} ]

sonata_seo:
    page:
        title: 'industrialmoving'
        metas:
            property:
                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:title':     industrialmoving
                'og:site_name':       industrialmoving
                'og:description':     industrialmoving описание
                'og:image':     http://industrialmoving.bg/images/logo.png
                'og:url':     http://industrialmoving.bg
                'og:type':     website
    sitemap:
        doctrine_orm:
            images:
                types: [image]
                route: sonata_media_view
                connection: doctrine.dbal.default_connection
                parameters:
                    id: null
                query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM media__media"
