# NTProjectsBundle routes
projects_bundle:
    resource: "@NTProjectsBundle/Controller"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

# NTNewsBundle routes
news_bundle:
    resource: "@NTNewsBundle/Controller"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

# NTDealersBundle routes
dealers_bundle:
    resource: "@NTDealersBundle/Controller"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

# NTSliderBundle routes
slider_bundle:
    resource: "@NTSliderBundle/Controller"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

# NTFrontendBundle routes
frontend_bundle:
    resource: "@NTFrontendBundle/Controller"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_show:
    pattern: /{_locale}/profile
    defaults: { _controller: ApplicationSonataUserBundle:FrontendProfile:edit }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

nt_content:
    resource: "@NTContentBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "[a-z]{2}"

nt_tiny_mce:
    resource: "@NTTinyMCEBundle/Controller/"
    type:     annotation

no_culture:
    pattern:   /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true # this is for 301
