<?php
/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;

class UserAdminController extends Controller
{
    /**
     * @throws \Symfony\Component\Security\Core\Exception\AccessDeniedException
     * @return \Symfony\Bundle\FrameworkBundle\Controller\Response|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request = null)
    {
        if (false === $this->admin->isGranted('CREATE')) {
            throw new AccessDeniedException();
        }

        $parameters = $this->admin->getPersistentParameters();

        if (!isset($parameters['type'])) {
            return $this->render('ApplicationSonataUserBundle:UserAdmin:select_type.html.twig', array(
                'types'     => array('U' => 'User', 'A' => 'Admin'),
                'base_template' => $this->getBaseTemplate(),
                'admin'         => $this->admin,
                'action'        => 'create'
            ));
        }

        return parent::createAction($request);
    }

    public function editAction($id = null, Request $request = null)
    {
        if (false === $this->admin->isGranted('EDIT')) {
            throw new AccessDeniedException();
        }
        
        $request->query->set('type', $this->isAdmin($this->admin->getSubject()) ? 'A' : 'U');

        return parent::editAction($id, $request); // TODO: Change the autogenerated stub
    }

    private function isAdmin($user)
    {
        $res = $user->hasRole('ROLE_SONATA_ADMIN') || $user->hasRole('ROLE_SUPER_ADMIN');
        if(!$res) {
            foreach ($user->getGroups() as $g) {
                $res = $g->hasRole('ROLE_SONATA_ADMIN') || $g->hasRole('ROLE_SUPER_ADMIN');
                if($res) break;
            }    
        }
        return $res;
        
    }

    /**
     * @param string                                          $view
     * @param array                                           $parameters
     * @param null|\Symfony\Component\HttpFoundation\Response $response
     *
     * @return \Symfony\Bundle\FrameworkBundle\Controller\Response
     */
    public function render($view, array $parameters = array(), Response $response = null, Request $request = null)
    {
        if($request != null) {
            $parameters['persistent_parameters'] = $this->admin->getPersistentParameters();

        }

        return parent::render($view, $parameters, $response, $request);
    }
}
